### ISSUE TITLE
Failed training the unsupervised segmentation network

### ISSUE THREAD

**Issue by rya2001** [jx-zhong-for-academic-purpose/Multibody_SE3#2]
I followed the readme to run your great work. I downloaded SAPIEN Dataset and used the provided ogc_ckpt to generate scene flow without any problem, then I tried to train the unsupervised segmentation network. At first the code could run properly, but after running 20 epochs an error showed up. I checked the code and found that after 20 epochs the network loss is calculated using `masks_weight` . It seems that there is a problem dealing with `masks_weight`. Please fix it!

BTW It will be very grateful if you could provide trained checkpoint files of your great work!

**Comment by jx-zhong-for-academic-purpose** [comment]
Could you provide the curve of the training loss? Sometimes training is not that stable. If so, please set EPOCH_NOT_JUST_SEG EPOCH_SUPERVISED_BY_R EPOCH_SUPERVISED_BY_R as larger numbers (eg 20 25 30) and use a small loss weight on https://github.com/jx-zhong-for-academic-purpose/Multibody_SE3/blob/7c6d4649e6fe14d2992ecef8a4cbe04951de9822/eq_train_2head_unsup.py#L256 (eg 1/10 -> 1/25) to stabilize the training process. It should help the network converge ...

**Comment by rya2001** [comment]
Thanks for the reply! I set EPOCH_NOT_JUST_SEG and EPOCH_SUPERVISED_BY_R to 25, and use 1/25 for loss weight. This time the same problem showed up when running 25th epoch. Here is the full traceback.
```bash
Traceback (most recent call last):
  File "eq_train_2head_unsup.py", line 669, in <module>
    trainer.train(args.epochs, train_set, train_loader, val_loader)
  File "eq_train_2head_unsup.py", line 420, in train
    loss_dict, segm, mask = self._train_it(it, batch, aug_transform=aug_transform)
  File "eq_train_2head_unsup.py", line 300, in _train_it
    loss, loss_dict = self.criterion(pcs, masks, temporal_ensemble_flows,
  File "/home/jkl/miniconda3/envs/mbse3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'masks_weight'
```
The loss curve for the finished 24 epochs:
![trainloss](https://github.com/user-attachments/assets/29c7a57f-318f-49aa-ac24-a1d8656b9bff)

**Comment by rya2001** [comment]
@jx-zhong-for-academic-purpose I have put the loss curves in reply, is there anything else I need to provide?
